### ISSUE TITLE
Any particular reason for lack of XP and prior compatibility?

### ISSUE THREAD

**Issue by TheColorOfFear** [Vortesys/Program-Manager-II#39]
There isn't really a discussion tab so I figured this would be the appropriate way to ask, is there any specific reason you're not going for NT3-5 compatibility?

**Comment by freedom7341** [comment]
Mostly up to localization functions since I want to have full MUI support. Partially because the original Program Manager already runs on those platforms as well. I use Windows Vista on some of my computers so I figured anything Vista and newer would be a good target. I don't think there's much if anything currently preventing Program Manager II from compiling on older versions of Windows, but I don't plan on supporting it, although I won't add artificial blocks or try to make it hard to run it on those versions.
